name: Build (Windows, GTK4 + Libadwaita)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows-gtk4:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain (GNU)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-gnu
          profile: minimal

      - name: Setup MSYS2 (UCRT64) and install GTK4 + libadwaita
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: UCRT64
          update: true
          cache: true
          install: >
            mingw-w64-ucrt-x86_64-toolchain

      # ---------- GNU ----------
      - name: Build with GNU toolchain
        run: |
          export CARGO_HOME="/c/Users/$(whoami)/.cargo"
          export PATH="$CARGO_HOME/bin:$PATH"

          rustup default stable-x86_64-pc-windows-gnu || true
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Show bindings.rs (GNU)
        run: |
          echo "=== GNU bindings.rs ==="
          find target -type f -name 'bindings.rs' -print
          for f in $(find target -type f -name 'bindings.rs'); do
            echo ">>> $f"
            cat "$f"
          done

      # ---------- MSVC ----------
      - name: Build with MSVC toolchain
        shell: pwsh
        run: |
          rustup default stable-x86_64-pc-windows-msvc
          rustup target add x86_64-pc-windows-msvc
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Show bindings.rs (MSVC)
        shell: pwsh
        run: |
          Write-Output "=== MSVC bindings.rs ==="
          Get-ChildItem -Recurse -Filter bindings.rs target | ForEach-Object {
            Write-Output ">>> $($_.FullName)"
            Get-Content $_.FullName
          }

      # ---------- Upload binaries (ton original) ----------
      - name: Collect artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-gtk4-binary
          path: target/*
